### ISSUE TITLE
create navbar

### ISSUE THREAD

**Issue by evanykauh** [cse110-sp24-group29/WarmUpExcercise#2]
Task List:

- [x] Create a professionally styled navigation bar (reflective of our group theme).
- [x] Put the team logo on the top left of the page (leftmost side of the navbar).
- [x] Create some non-active links for possible webpages: Home, About Us, Contact Us, Provide Feedback (this one should be different in colour than the rest of the links, suggesting this is active).
- [x] Add redirection for Contact Us link so that is redirects the user to the "Contact Us" section on the same page.

**Comment by sakshamrai101** [comment]
Resolved.
